hampter = {"health":1, "attack":0, "blood":0, "bones":0, "enchantment":0}
bulletAnt = {"health":1, "attack":1, "blood":1, "bones":0, "enchantment":0} # Talks
pineMartin = {"health":2, "attack":1, "blood":1, "bones":0, "enchantment":0} # Talks
seal = {"health":3, "attack":1, "blood":2, "bones":0, "enchantment":0} # Talks
deer = {"health":3, "attack":2, "blood":0, "bones":3, "enchantment":0}
goblinShark = {"health":2, "attack":2, "blood":2, "bones":0, "enchantment":0}
adder = {"health":1, "attack":2, "blood":0, "bones":4, "enchantment":0}
flyingFish = {"health":1, "attack":1, "blood":1, "bones":0, "enchantment":0}
scorpionFish = {"health":1, "attack":2, "blood":2, "bones":0, "enchantment":0}
stoneFish = {"health":1, "attack":2, "blood":2, "bones":0, "enchantment":0}
jerboa = {"health":1, "attack":1, "blood":0, "bones":1, "enchantment":0}
blobFish = {"health":4, "attack":0, "blood":3, "bones":0, "enchantment":0}
armadillo  = {"health":4, "attack":1, "blood":3, "bones":0, "enchantment":0}
opossum  = {"health":1, "attack":1, "blood":1, "bones":0, "enchantment":0}
mimicOctopus = {"health":0, "attack":0, "blood":2, "bones":0, "enchantment":0} # Mirrors opponent stats 
mongoose = {"health":2, "attack":1, "blood":1, "bones":0, "enchantment":0}
slowLorris = {"health":1, "attack":3, "blood":2, "bones":0, "enchantment":0}
axolotl = {"health":1, "attack":1, "blood":1, "bones":0, "enchantment":0}
wolverine = {"health":2, "attack":2, "blood":2, "bones":0, "enchantment":0}
hedgehog = {"health":1, "attack":1, "blood":1, "bones":0, "enchantment":0}
pinkFairyArmadillo = {"health":1, "attack":1, "blood":0, "bones":0, "enchantment":0} # Dies if near water
narwhal = {"health":3, "attack":3, "blood":3, "bones":0, "enchantment":0}
shoebill = {"health":1, "attack":2, "blood":0, "bones":3, "enchantment":0}
beardedDragon = {"health":2, "attack":1, "blood":1, "bones":0, "enchantment":0}
gilaMonster = {"health":2, "attack":2, "blood":2, "bones":0, "enchantment":0}
tapir = {"health":3, "attack":1, "blood":2, "bones":0, "enchantment":0}
platypus = {"health":2, "attack":2, "blood":2, "bones":0, "enchantment":0}
rhino = {"health":6, "attack":2, "blood":4, "bones":0, "enchantment":0}
anteater = {"health":2, "attack":1, "blood":1, "bones":0, "enchantment":0}
mole = {"health":1, "attack":0, "blood":0, "bones":0, "enchantment":0}
capybara = {"health":2, "attack":1, "blood":1, "bones":0, "enchantment":0}
polarBear = {"health":4, "attack":4, "blood":4, "bones":0, "enchantment":0}
proboscisMonkey = {"health":3, "attack":2, "blood":3, "bones":0, "enchantment":0}
brianCoral = {"health":4, "attack":0, "blood":0, "bones":4, "enchantment":0} # Says: "Hi, I'm Brian"
phoenix = {"health":1, "attack":1, "blood":2, "bones":0, "enchantment":0} # Gains 1 health and attack each time it dies
